import { useEffect, useState } from "react";
import type { Group, Material, Note, VaporSettings, VaporSource } from "../../domain/models";
import { noteMeta, tagIdsFor, uid } from "../../domain/formula";
import { defaultVaporSettings } from "../../domain/fixtures";
import { Field } from "../../components/common/FormControls";
import { GroupBar, TagDisplay, TagEditor, TagPicker } from "../../components/tags/TagControls";
import { syncLocalStore } from "../../services/localStore";

export function Materials({materials,groups,query,onAdd,onEdit,onDelete,onNewGroup,onDeleteGroup,onAssign}:{materials:Material[];groups:Group[];query:string;onAdd:()=>void;onEdit:(m:Material)=>void;onDelete:(ids:string[])=>void;onNewGroup:()=>void;onDeleteGroup:(id:string)=>void;onAssign:(id:string,tagId:string)=>void}){
    const [active,setActive]=useState("all"),[selectedIds,setSelectedIds]=useState<string[]>([]),[toneFocus,setToneFocus]=useState<Note|null>(null),[typeFocus,setTypeFocus]=useState<"all"|"synthetic"|"natural"|"accord">("all"),[sortMode,setSortMode]=useState<"time"|"note"|"vapor">("time"),[sortDirection,setSortDirection]=useState<"asc"|"desc">("desc"),[vaporWarning,setVaporWarning]=useState(false);
    const hasVapor=(m:Material)=>m.vaporPressure!==undefined&&m.vaporPressure!==""&&Number.isFinite(Number(m.vaporPressure))&&Number(m.vaporPressure)>=0;
    const scoped=materials.filter(m=>(m.cn+m.en).toLowerCase().includes(query.toLowerCase())&&(active==="all"||(active==="ungrouped"?!tagIdsFor(m).length:tagIdsFor(m).includes(active))));
    const visible=scoped.filter(m=>typeFocus==="all"||(m.materialType||"synthetic")===typeFocus);
    const noteOrder:Record<Note,number>={top:0,heart:1,base:2},originalOrder=new Map(materials.map((m,i)=>[m.id,i]));
    const ordered=[...visible].sort((a,b)=>{if(toneFocus){const ap=a.note===toneFocus?0:1,bp=b.note===toneFocus?0:1;if(ap!==bp)return ap-bp}if(sortMode==="vapor"){const bucket=(m:Material)=>hasVapor(m)?(Number(m.vaporPressure)>=50?0:Number(m.vaporPressure)>=.5?2:4):(m.note==="top"?1:m.note==="heart"?3:5),ab=bucket(a),bb=bucket(b);if(ab!==bb)return sortDirection==="desc"?ab-bb:bb-ab;if(hasVapor(a)&&hasVapor(b))return sortDirection==="desc"?Number(b.vaporPressure)-Number(a.vaporPressure):Number(a.vaporPressure)-Number(b.vaporPressure);return 0}const av=sortMode==="note"?noteOrder[a.note]:(a.createdAt?Date.parse(a.createdAt):-(originalOrder.get(a.id)||0)),bv=sortMode==="note"?noteOrder[b.note]:(b.createdAt?Date.parse(b.createdAt):-(originalOrder.get(b.id)||0));return sortDirection==="asc"?av-bv:bv-av});
    const toggle=(id:string)=>setSelectedIds(ids=>ids.includes(id)?ids.filter(v=>v!==id):[...ids,id]),typeName=(m:Material)=>m.materialType==="natural"?"天然香料":m.materialType==="accord"?"香基":"人工香料",chooseVapor=()=>{if(!visible.some(hasVapor)){setVaporWarning(true);return}setVaporWarning(false);setSortMode("vapor")};
    const typeOptions=[["all","全部"],["synthetic","人工香料"],["natural","天然香料"],["accord","香基"]] as const;
    return <div className="materialPage">
      <div className="titleline"><div><p>原料库</p><h1>我的香料</h1></div><span>{visible.length} 种原料</span></div>
      <GroupBar groups={groups} active={active} onChange={setActive} onNew={onNewGroup} onDelete={id=>{if(active===id)setActive("all");onDeleteGroup(id)}}/>
      <div className="materialTypeFilters">{typeOptions.map(([value,label])=><button key={value} className={typeFocus===value?"on":""} onClick={()=>setTypeFocus(value)} aria-pressed={typeFocus===value}><span>{label}</span><b>{scoped.filter(m=>value==="all"||(m.materialType||"synthetic")===value).length}</b></button>)}</div>
      {selectedIds.length>0&&<div className="batchBar"><b>已选择 {selectedIds.length} 种原料</b><button onClick={()=>setSelectedIds([])}>取消选择</button><button className="batchDelete" onClick={()=>{onDelete(selectedIds);setSelectedIds([])}}>删除所选原料</button></div>}
      <div className="materialStats">{(["top","heart","base"] as Note[]).map(n=><button className={toneFocus===n?"active":""} key={n} onClick={()=>setToneFocus(v=>v===n?null:n)}><small>{noteMeta[n].label}</small><b>{visible.filter(m=>m.note===n).length}</b><span>{noteMeta[n].sub}</span></button>)}</div>
      <div className="materialSort"><span>排序方式</span><div className="seg sortKinds"><button className={sortMode==="time"?"on":""} onClick={()=>{setSortMode("time");setVaporWarning(false)}}>加入时间</button><button className={sortMode==="note"?"on":""} onClick={()=>{setSortMode("note");setVaporWarning(false)}}>前中后调</button><button className={sortMode==="vapor"?"on":""} onClick={chooseVapor}>蒸气压</button></div><div className="seg direction"><button className={sortDirection==="asc"?"on":""} onClick={()=>setSortDirection("asc")}>顺序</button><button className={sortDirection==="desc"?"on":""} onClick={()=>setSortDirection("desc")}>倒序</button></div>{toneFocus&&<em>优先显示{noteMeta[toneFocus].label}</em>}</div>
      {vaporWarning&&<div className="sortWarning"><b>无法按蒸气压排序</b><span>当前范围内的原料均未设置有效蒸气压，已保留原排序方式。</span></div>}
      <div className="materialGrid">{ordered.map(m=><article className={`editableMaterial ${toneFocus&&m.note!==toneFocus?"toneMuted":""} ${sortMode==="vapor"&&!hasVapor(m)?"vaporMuted":""}`} key={m.id} onClick={()=>onEdit(m)}><label className="materialCheck" onClick={e=>e.stopPropagation()}><input type="checkbox" checked={selectedIds.includes(m.id)} onChange={()=>toggle(m.id)}/></label><div className={`dot ${m.note}`}/><span className="use">{noteMeta[m.note].label}</span><h3>{m.cn}</h3><p>{m.en}</p><div className="materialTypeMeta"><small>{typeName(m)}</small>{m.materialType==="synthetic"&&m.vaporPressure&&<small>蒸气压 {m.vaporPressure} Pa（25℃）</small>}</div>{m.diluted?<small>{m.concentration}% · {m.solvent}</small>:<small>原液 / 未稀释</small>}<TagDisplay groups={groups} selected={tagIdsFor(m)}/></article>)}<button className="newMaterial" onClick={onAdd}>＋<span>添加新原料</span></button></div>
    </div>;
}

export function MaterialModal({ initial, groups, onCreateTag, onClose, onSave }: {
    initial: Material | null;
    groups: Group[];
    onCreateTag: (name: string) => Promise<string>;
    onClose: () => void;
    onSave: (m: Material) => Promise<void> | void;
}) {
    const [m,setM]=useState<Material>(initial?{materialType:"synthetic",...initial}:{id:uid(),cn:"",en:"",note:"top",diluted:false,solvent:"无水乙醇",concentration:"10",materialType:"synthetic",vaporPressure:"",tagIds:[],createdAt:new Date().toISOString()});
    const [lookup,setLookup]=useState<"idle"|"loading"|"success"|"notice"|"error">("idle");
    const [message,setMessage]=useState("");
    const [saveMessage,setSaveMessage]=useState("");
    const [lookupSettings,setLookupSettings]=useState<VaporSettings>(defaultVaporSettings);
    const [settingsOpen,setSettingsOpen]=useState(false);
    const [settingsStatus,setSettingsStatus]=useState("");
    const [hoveredMaterialType,setHoveredMaterialType]=useState<Material["materialType"]|null>(null);
    const [hoveredNote,setHoveredNote]=useState<Note|null>(null);
    useEffect(()=>{syncLocalStore("list").then((data:{settings?:VaporSettings[]})=>{const saved=data.settings?.find(item=>item.id==="vapor_lookup");if(saved?.sources?.length)setLookupSettings(saved)}).catch(()=>{})},[]);
    const updateSource=(id:string,patch:Partial<VaporSource>)=>setLookupSettings(value=>({...value,sources:value.sources.map(source=>source.id===id?{...source,...patch}:source)}));
    const moveSource=(index:number,direction:-1|1)=>setLookupSettings(value=>{const next=[...value.sources],target=index+direction;if(target<0||target>=next.length)return value;[next[index],next[target]]=[next[target],next[index]];return{...value,sources:next}});
    const addSource=()=>setLookupSettings(value=>({...value,sources:[...value.sources,{id:uid(),name:"自定义网站",url:"https://"}]}));
    const saveLookupSettings=async()=>{setSettingsStatus("正在保存…");try{const cleaned={...lookupSettings,sources:lookupSettings.sources.map(source=>({...source,name:source.name.trim()||"自定义网站",url:source.url.trim()})).filter(source=>/^https?:\/\//i.test(source.url))};if(!cleaned.sources.length)throw new Error("请至少保留一个有效网址。");await syncLocalStore("save",{kind:"settings",record:cleaned});setLookupSettings(cleaned);setSettingsStatus("设置已保存")}catch(error){setSettingsStatus(error instanceof Error?error.message:"保存失败")}};
    const toggleTag=(id:string)=>setM(v=>{const ids=tagIdsFor(v);return{...v,groupId:undefined,tagIds:ids.includes(id)?ids.filter(x=>x!==id):[...ids,id]}});
    const autoFill=async()=>{setLookup("notice");setMessage("桌面版暂未接入在线查询，请先手动填写；该功能会在后续本地服务层中恢复。");};
    const save=async()=>{setSaveMessage("");try{const {latinName:_latinName,cas:_cas,supplier:_supplier,referenceUrl:_referenceUrl,...record}=m;await onSave({...record,cn:m.cn.trim(),en:m.en.trim()})}catch(error){setSaveMessage(error instanceof Error?error.message:"保存失败，请稍后重试。")}};
    if(settingsOpen)return <div className="modal"><div className="dialog vaporSettingsDialog"><div className="modalHead"><div><small>LOOKUP SETTINGS</small><h2>蒸气压爬取设置</h2></div><button onClick={()=>setSettingsOpen(false)}>×</button></div><div className="modalForm"><p className="settingsHint">从上到下表示优先级。明确的25℃数据会优先于非25℃结果。</p><div className="sourceList">{lookupSettings.sources.map((source,index)=><div className="sourceItem" key={source.id}><span>{index+1}</span><div><input aria-label="网站名称" value={source.name} onChange={e=>updateSource(source.id,{name:e.target.value})}/><input aria-label="网站网址" value={source.url} onChange={e=>updateSource(source.id,{url:e.target.value})}/></div><div className="sourceActions"><button disabled={index===0} onClick={()=>moveSource(index,-1)}>↑</button><button disabled={index===lookupSettings.sources.length-1} onClick={()=>moveSource(index,1)}>↓</button><button disabled={lookupSettings.sources.length===1} onClick={()=>setLookupSettings(value=>({...value,sources:value.sources.filter(item=>item.id!==source.id)}))}>−</button></div></div>)}</div><button className="addSourceButton" onClick={addSource}>＋ 添加爬取网站</button><label className="fallbackSwitch"><input type="checkbox" checked={lookupSettings.broadSearch} onChange={e=>setLookupSettings(value=>({...value,broadSearch:e.target.checked}))}/><span><b>允许全网兜底搜索</b><small>默认网站均无结果时，再尝试其它网址和搜索引擎。查询时间可能更长。</small></span></label>{settingsStatus&&<small className="settingsStatus">{settingsStatus}</small>}</div><div className="modalActions"><button onClick={()=>setSettingsOpen(false)}>返回</button><button className="primary" onClick={saveLookupSettings}>保存设置</button></div></div></div>;
    return <div className="modal"><div className="dialog"><div className="modalHead"><div><small>RAW MATERIAL</small><h2>{initial?"编辑原料":"添加原料"}</h2></div><button onClick={onClose}>×</button></div><div className="modalForm"><Field label="中文名称"><input autoFocus value={m.cn} onChange={e=>setM({...m,cn:e.target.value})}/></Field><Field label="英文名称"><input value={m.en} onChange={e=>setM({...m,en:e.target.value})}/></Field><Field label="香料类型"><div className="seg three explicitHover">{([['synthetic','人工香料'],['natural','天然香料'],['accord','香基']] as const).map(([value,label])=><button key={value} className={`${m.materialType===value?"on":""} ${hoveredMaterialType===value?"isHovered":""}`} onMouseEnter={()=>setHoveredMaterialType(value)} onMouseLeave={()=>setHoveredMaterialType(null)} onClick={()=>setM({...m,materialType:value,vaporPressure:value==="synthetic"?m.vaporPressure:""})}>{label}</button>)}</div></Field>{m.materialType==="synthetic"&&<Field label="蒸气压（25℃）"><div className="vaporLookupRow"><div className="unitInput"><input type="number" min="0" step="any" value={m.vaporPressure||""} onChange={e=>setM({...m,vaporPressure:e.target.value})}/><b>Pa</b></div><button type="button" disabled={lookup==="loading"||(!m.cn.trim()&&!m.en.trim())} onClick={autoFill}>{lookup==="loading"?"查询中…":"自动补全"}</button><button type="button" className="lookupSettingsButton" onClick={()=>setSettingsOpen(true)} aria-label="蒸气压爬取设置">设置</button></div>{message&&<small className={`vaporLookupMessage ${lookup}`}>{message}</small>}</Field>}<Field label="香调分类"><div className="seg three explicitHover">{(["top","heart","base"] as Note[]).map(n=><button key={n} className={`${m.note===n?"on":""} ${hoveredNote===n?"isHovered":""}`} onMouseEnter={()=>setHoveredNote(n)} onMouseLeave={()=>setHoveredNote(null)} onClick={()=>setM({...m,note:n})}>{noteMeta[n].label}</button>)}</div></Field><label className="check"><input type="checkbox" checked={m.diluted} onChange={e=>setM({...m,diluted:e.target.checked})}/><span>这是已稀释的香料</span></label>{m.diluted&&<div className="twocol"><Field label="溶剂"><input value={m.solvent} onChange={e=>setM({...m,solvent:e.target.value})}/></Field><Field label="浓度"><div className="unitInput"><input value={m.concentration} onChange={e=>setM({...m,concentration:e.target.value})}/><b>%</b></div></Field></div>}<TagEditor groups={groups} selected={tagIdsFor(m)} onToggle={toggleTag} onCreate={onCreateTag}/>{saveMessage&&<div className="sortWarning"><b>{saveMessage}</b></div>}</div><div className="modalActions"><button onClick={onClose}>取消</button><button className="primary" disabled={!m.cn.trim()} onClick={save}>{initial?"保存修改":"保存原料"}</button></div></div></div>;
}
